# fly.toml app configuration file generated for question-marks-reply-bot-rs on 2023-12-02T09:24:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "question-marks-reply-bot-rs"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[mounts]]
  source="data"
  destination="/data"

[[env]]
  QUESTION_MARKS_REPLY_BOT_RS_ADDRESS = "[::]:8080"
  RUST_LOG = "info"